apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
  namespace: rafi-namespace
spec:
  type: LoadBalancer
  selector:
    app: bookmyshow
  ports:
    - port: 80        # external port
      targetPort: 80 # container port
